### ISSUE TITLE
Identity API, Oauth2 and security issues

### ISSUE THREAD

**Issue by jjperezaguinaga** [GoogleChrome/chrome-app-samples#123]
Is there any *safe* place where we can put our Client Secret Id's inside the application? I think that having it [here](https://github.com/GoogleChrome/chrome-app-samples/blob/master/github-auth/index.js) is a terrible idea (Github Auth sample); anyone that sees that repo might think putting their client Id's there is a good idea and carry that practice to their applications whenever the Identity API gets out of Beta.

At the beginning I thought the manifest.json was a good option, but you can easily get its contents with chrome.runtime.getManifest(). I hope we can really avoid having to set up a server for each of our apps...

**Comment by beaufortfrancois** [comment]
The issue here is that as @ajaythomas123 showed me, anyone with your client id *and* secret can revoke all authorizations of your application with a simple HTTP request:
https://developer.github.com/v3/oauth_authorizations/#revoke-all-authorizations-for-an-application

Also, they could drain the unauthenticated rate limit quota for your application:
https://developer.github.com/v3/#increasing-the-unauthenticated-rate-limit-for-oauth-applications

@fgorski @mangini As it's kinda easy to introspect a Chrome App, we may not want to show developers that `clientSecret` can be stored as plain text as it's mentioned in the GitHub Auth Sample: https://github.com/GoogleChrome/chrome-app-samples/blob/2ea479ff58b7aa88a4c6374815da33f8f56f7de6/samples/github-auth/index.js#L12

**Comment by fgorski** [comment]
Regarding the client ID and Secret placed in code.
We can add a comment that this is just for sample purposes and that they
should secure these value according to documentation located *where*?

As for not putting our secret and ID in the code, we can of course replace
them with dummy values. (The developer playing around with the samples is
supposed to).

**Comment by beaufortfrancois** [comment]
Thanks!
Fixed in https://github.com/GoogleChrome/chrome-app-samples/commit/660ef3b642a77f04d6df8e29a48e6465a686c886

**Comment by staff0rd** [comment]
Isn't the Github Auth Sample actually terribly misleading?  What method exists to securely store and/or pass the client secret in a Chrome extension?  If there isn't one, why does the example exist?

**Comment by johnyoonh** [comment]
@staff0rd I think if there was a better way, these guys would have told you, but I came empty handed in my searches. Unless Google provides a way to upload client key / secret on Chrome Developer account, obfuscation and then limiting the privileges on the server side for that specific key-pair is the best thing you can do.
