### ISSUE TITLE
gcm messages are not displayed in the browser

### ISSUE THREAD

**Issue by jamaalscarlett** [GoogleChrome/chrome-app-samples#401]
I registered the device using the extension and received a registration id.  But when I send the message I get no error:
id=0:1434721938072310%a524d9bef9fd7ecd
but there is no notification displayed.  When I turn on logging with chrome://gcm-internals in see this message: No such registered app found

![screen shot 2015-06-19 at 10 09 25 am](https://cloud.githubusercontent.com/assets/7093153/8255003/e2907956-166a-11e5-9c44-fcf0776242b1.jpg)

I have tried using gcm through chrome extensions on 3 seperate machines, only the first machine is properly receiving the messages.

**Comment by mohammedpascal** [comment]
I am facing the same problem! I get no such registered app found even though it's exists I think it's a bug in the latest chrome, check the version of your chrome on first machine?

**Comment by jamaalscarlett** [comment]
Both were running the same version

**Comment by beaufortfrancois** [comment]
@fgorski might be able to help there.

**Comment by fgorski** [comment]
Based on response to https://github.com/google/gcm/issues/65 there was an insfrastructur eissue affecting mostly Chrome users. It should have been fixed by now according to internal bug tracker.

Please use this bug for further comments: https://code.google.com/p/chromium/issues/detail?id=503186

mohammedpascal@ could you confirm that this is not a separate problem from the one above you reported?

**Comment by jamaalscarlett** [comment]
Thank you. It appears to be working.
